### PR TITLE
update json-schema gem version

### PR DESCRIPTION
**Pull request by mainameiz**

### CODE REVIEW

**Comment by submitteddenied** [comment]
Hi @mainameiz, what has changed in json-schema that you're updating for?

**Comment by mainameiz** [comment]
It fixes this error

```
Failure/Error: expect(response.body).to match_json_schema(schema_name, fragment: fragment)
     JSON::Schema::SchemaError:
       This library does not have support for schemas defined by http://interagent.github.io/interagent-hyper-schema
```

But I didnt go deeper in what was a reason for that error.

**Comment by mcordell** [comment]
I experience a similar bug:

```
   Failure/Error: expect(response.body).to match_json_schema(:conversation, strict: true)
     ArgumentError:
       wrong number of arguments (2 for 1)
```

Updating the Gemfile to point at master on github resolves this.

**Comment by russellcardullo** [comment]
Thanks @mainameiz, merging this.

**Comment by jhass** [comment]
:+1:  Can we have a release?

**Comment by russellcardullo** [comment]
@jhass Just pushed a release.  Thanks!

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
